name: CI/CD Pipeline

on:
  push:
    branches:
      - develop



jobs:
  lint:
    name: PHP Lint
    runs-on: self-hosted  # Utilisation de votre runner self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Lint PHP files
        run: |
          for file in $(find . -name "*.php"); do
            php -l "$file" || exit 1
          done

  build:
    name: Build Docker Image
    needs: lint  # S'exécute après le lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Build image
        run: |
          docker build -t my-php-app:${{ github.sha }} .
          # On sauvegarde temporairement l'image pour le job suivant
          docker save my-php-app:${{ github.sha }} > /tmp/my-php-app.tar

  push:
    name: Push to Local Registry
    needs: build
    runs-on: self-hosted
    steps:
      - name: Load saved image
        run: docker load < /tmp/my-php-app.tar
      
      - name: Tag and push to local registry
        run: |
          docker tag my-php-app:${{ github.sha }} localhost:5000/my-php-app:latest
          docker push localhost:5000/my-php-app:latest



  
